#!/usr/bin/env bash
# generate-compose.sh
# Generates a docker-compose.yml for N ZKsync OS L2 chains.

set -euo pipefail

COUNT=2
VERSION="v30.2"
CONFIGS_DIR="./configs/v30.2"
SERVER_IMAGE="ghcr.io/matter-labs/zksync-os-server:latest"
L1_IMAGE="ghcr.io/foundry-rs/foundry:v1.3.4"
OUTPUT="docker-compose.generated.yml"
BASE_CHAIN_ID=6564  # chain N gets ID BASE_CHAIN_ID + N

for arg in "$@"; do
  case "$arg" in
    --count=*)        COUNT="${arg#*=}" ;;
    --version=*)      VERSION="${arg#*=}" ;;
    --configs-dir=*)  CONFIGS_DIR="${arg#*=}" ;;
    --server-image=*) SERVER_IMAGE="${arg#*=}" ;;
    --l1-image=*)     L1_IMAGE="${arg#*=}" ;;
    --output=*)       OUTPUT="${arg#*=}" ;;
  esac
done

# Resolve absolute path for configs dir (needed for volume mounts)
CONFIGS_DIR="$(realpath "$CONFIGS_DIR")"

cat > "$OUTPUT" <<'HEADER'
# Auto-generated by configure-l2s
# Do not edit manually - re-run configure-l2s to regenerate.
#
# Services:
#   l1        - Local L1 (Anvil), port 5010
#   chain-*   - ZKsync OS L2 chains
HEADER

cat >> "$OUTPUT" <<COMPOSE_START

name: zksync-three-chains-problem

services:
  l1:
    image: $L1_IMAGE
    volumes:
      - $CONFIGS_DIR/l1-state.json.gz:/l1-state.json.gz:ro
      - l1state:/home/foundry/l1state
    entrypoint: ''
    user: 'root'
    ports:
      - '5010:5010'
    healthcheck:
      test: ['CMD-SHELL', 'cast chain-id -r http://localhost:5010']
      interval: 10s
      timeout: 5s
      retries: 5
    command: |
      bash -c "
      if [[ ! -f /home/foundry/l1state/state.json ]]; then
        echo 'Decompressing L1 state...'
        gzip -d < /l1-state.json.gz > /home/foundry/l1state/state.json
      fi
      anvil --state=/home/foundry/l1state/state.json --port 5010 --host 0.0.0.0
      "

COMPOSE_START

# Generate a service for each chain
for i in $(seq 1 "$COUNT"); do
  CHAIN_ID=$((BASE_CHAIN_ID + i))
  INT_PORT=$((3049 + i))   # 3050, 3051, 3052, ...
  EXT_PORT=$((5049 + i))   # 5050, 5051, 5052, ...
  DB_VOLUME="chain_${CHAIN_ID}_db"

  cat >> "$OUTPUT" <<CHAIN_SERVICE
  chain-${CHAIN_ID}:
    image: $SERVER_IMAGE
    platform: linux/amd64
    ports:
      - '${EXT_PORT}:${INT_PORT}'
    environment:
      GENERAL_L1_RPC_URL: 'http://l1:5010'
    user: 'root'
    working_dir: '/app'
    entrypoint: ''
    command: ['/usr/bin/tini', '--', 'zksync-os-server', '--config', '/configs/chain_${CHAIN_ID}.yaml']
    volumes:
      - ${DB_VOLUME}:/db
      - $CONFIGS_DIR/chain_${CHAIN_ID}.yaml:/configs/chain_${CHAIN_ID}.yaml:ro
      - $CONFIGS_DIR/genesis.json:/app/local-chains/${VERSION}/genesis.json:ro
    depends_on:
      l1:
        condition: service_healthy
    healthcheck:
      test: ['CMD', '/usr/bin/bash', '-c', 'exec 3<>/dev/tcp/127.0.0.1/${INT_PORT}']
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s

CHAIN_SERVICE
done

# Volumes section
echo "volumes:" >> "$OUTPUT"
echo "  l1state:" >> "$OUTPUT"
for i in $(seq 1 "$COUNT"); do
  CHAIN_ID=$((BASE_CHAIN_ID + i))
  echo "  chain_${CHAIN_ID}_db:" >> "$OUTPUT"
done

echo "Generated $OUTPUT with $COUNT chain(s)."
