#!/usr/bin/env bash
# generate-compose.sh
# Generates composable docker-compose files for N ZKsync OS L2 chains:
#   <output-dir>/docker-compose.l1.yml
#   <output-dir>/docker-compose.gateway-506.yml    (gateway mode only)
#   <output-dir>/docker-compose.zksyncos-<id>.yml  (one per chain)

set -euo pipefail

readonly SCRIPT_NAME="generate-compose.sh"

# ── defaults ──────────────────────────────────────────────────────────────────
readonly DEFAULT_COUNT=2
readonly DEFAULT_VERSION="v30.2"
readonly DEFAULT_SERVER_IMAGE="ghcr.io/matter-labs/zksync-os-server:latest"
readonly DEFAULT_L1_IMAGE="ghcr.io/foundry-rs/foundry:v1.3.4"
readonly BASE_CHAIN_ID=6564

readonly GATEWAY_CHAIN_ID=506
readonly GATEWAY_INTERNAL_PORT=3052
readonly GATEWAY_EXTERNAL_PORT=5049   # host-visible port for the gateway RPC

# ── helpers ───────────────────────────────────────────────────────────────────
die()        { echo "[$SCRIPT_NAME] ERROR: $*" >&2; exit 1; }
log()        { echo "[$SCRIPT_NAME] $*"; }
is_integer() { [[ "$1" =~ ^[0-9]+$ ]]; }

usage() {
  cat <<EOF
Usage: $SCRIPT_NAME [OPTIONS]

Generates composable docker-compose files for N ZKsync OS L2 chains.

Options:
  --count=N           Number of L2 chains (default: $DEFAULT_COUNT)
  --output-dir=DIR    Directory to write compose files into (required)
  --configs-dir=DIR   Directory containing chain configs and genesis (required)
  --version=VER       ZKsync OS version (default: $DEFAULT_VERSION)
  --server-image=IMG  zksync-os-server Docker image (default: $DEFAULT_SERVER_IMAGE)
  --l1-image=IMG      L1 / Anvil Docker image (default: $DEFAULT_L1_IMAGE)
  --gateway           Add a gateway chain (506) service; L2 chains depend on it
  --help, -h          Show this message

Output files:
  <output-dir>/docker-compose.l1.yml
  <output-dir>/docker-compose.gateway-506.yml        (only with --gateway)
  <output-dir>/docker-compose.zksyncos-<id>.yml      (one per chain)
EOF
  exit 0
}

# ── argument parsing ──────────────────────────────────────────────────────────
count="$DEFAULT_COUNT"
output_dir=""
configs_dir=""
version="$DEFAULT_VERSION"
server_image="$DEFAULT_SERVER_IMAGE"
l1_image="$DEFAULT_L1_IMAGE"
gateway=false

for arg in "$@"; do
  case "$arg" in
    --count=*)        count="${arg#*=}" ;;
    --output-dir=*)   output_dir="${arg#*=}" ;;
    --configs-dir=*)  configs_dir="${arg#*=}" ;;
    --version=*)      version="${arg#*=}" ;;
    --server-image=*) server_image="${arg#*=}" ;;
    --l1-image=*)     l1_image="${arg#*=}" ;;
    --gateway)        gateway=true ;;
    --help|-h)        usage ;;
    *) die "Unknown argument: $arg" ;;
  esac
done

[[ -n "$output_dir"  ]] || die "--output-dir is required"
[[ -n "$configs_dir" ]] || die "--configs-dir is required"
is_integer "$count"    || die "--count must be a positive integer"
[[ "$count" -ge 1 ]]   || die "--count must be at least 1"

configs_dir="$(realpath "$configs_dir")"
mkdir -p "$output_dir"

# ── l1 compose file ───────────────────────────────────────────────────────────
generate_l1() {
  local -r out="$output_dir/docker-compose.l1.yml"
  cat > "$out" <<EOF
# Auto-generated by $SCRIPT_NAME — do not edit manually.
name: zksync-l2s

services:
  l1:
    image: $l1_image
    volumes:
      - $configs_dir/l1-state.json.gz:/l1-state.json.gz:ro
      - l1state:/home/foundry/l1state
    entrypoint: ''
    user: 'root'
    ports:
      - '5010:5010'
    healthcheck:
      test: ['CMD-SHELL', 'cast chain-id -r http://localhost:5010']
      interval: 10s
      timeout: 5s
      retries: 5
    command: |
      bash -c "
      if [[ ! -f /home/foundry/l1state/state.json ]]; then
        echo 'Decompressing L1 state...'
        gzip -d < /l1-state.json.gz > /home/foundry/l1state/state.json
      fi
      anvil --state=/home/foundry/l1state/state.json --preserve-historical-states --port 5010 --host 0.0.0.0
      "

volumes:
  l1state:
EOF
  log "Generated $out"
}

# ── gateway compose file ──────────────────────────────────────────────────────
# The gateway chain (506) settles to L1 and serves as the settlement layer for L2 chains.
# L2 chains in gateway mode submit their batches here instead of directly to L1.
generate_gateway() {
  local -r out="$output_dir/docker-compose.gateway-506.yml"
  cat > "$out" <<EOF
# Auto-generated by $SCRIPT_NAME — do not edit manually.
# Gateway chain (ID: $GATEWAY_CHAIN_ID) — settles to L1; L2 chains settle here.
# See: https://github.com/matter-labs/zksync-os-server/tree/main/local-chains/v31.0/gateway
name: zksync-l2s

services:
  gateway-${GATEWAY_CHAIN_ID}:
    image: $server_image
    platform: linux/amd64
    ports:
      - '${GATEWAY_EXTERNAL_PORT}:${GATEWAY_INTERNAL_PORT}'
    environment:
      GENERAL_L1_RPC_URL: 'http://l1:5010'
    user: 'root'
    working_dir: '/app'
    entrypoint: ''
    command: ['/usr/bin/tini', '--', 'zksync-os-server', '--config', '/configs/chain_${GATEWAY_CHAIN_ID}.yaml']
    volumes:
      - gateway_${GATEWAY_CHAIN_ID}_db:/db
      - $configs_dir/chain_${GATEWAY_CHAIN_ID}.yaml:/configs/chain_${GATEWAY_CHAIN_ID}.yaml:ro
      - $configs_dir/genesis.json:/app/local-chains/${version}/genesis.json:ro
      - $configs_dir/gateway-db.tar.gz:/app/local-chains/${version}/gateway-db.tar.gz:ro
    depends_on:
      l1:
        condition: service_healthy
    healthcheck:
      test: ['CMD', '/usr/bin/bash', '-c', 'exec 3<>/dev/tcp/127.0.0.1/${GATEWAY_INTERNAL_PORT}']
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s

volumes:
  gateway_${GATEWAY_CHAIN_ID}_db:
EOF
  log "Generated $out"
}

# ── per-chain compose file ────────────────────────────────────────────────────
generate_chain() {
  local -r chain_num="$1"
  local -r chain_id=$(( BASE_CHAIN_ID + chain_num ))
  local -r int_port=$(( 3049 + chain_num ))   # 3050, 3051, 3052, ...
  local -r ext_port=$(( 5049 + chain_num ))   # 5050, 5051, 5052, ...
  local -r db_vol="zksyncos_${chain_id}_db"
  local -r out="$output_dir/docker-compose.zksyncos-${chain_id}.yml"

  # In gateway mode, L2 chains must wait for the gateway to be healthy
  local gateway_dep=""
  if [[ "$gateway" == true ]]; then
    gateway_dep="
      gateway-${GATEWAY_CHAIN_ID}:
        condition: service_healthy"
  fi

  cat > "$out" <<EOF
# Auto-generated by $SCRIPT_NAME — do not edit manually.
# Chain ID: $chain_id  |  RPC: localhost:$ext_port${gateway:+  |  Settles to: gateway-$GATEWAY_CHAIN_ID}
name: zksync-l2s

services:
  zksyncos-${chain_id}:
    image: $server_image
    platform: linux/amd64
    ports:
      - '${ext_port}:${int_port}'
    environment:
      GENERAL_L1_RPC_URL: 'http://l1:5010'
    user: 'root'
    working_dir: '/app'
    entrypoint: ''
    command: ['/usr/bin/tini', '--', 'zksync-os-server', '--config', '/configs/chain_${chain_id}.yaml']
    volumes:
      - ${db_vol}:/db
      - $configs_dir/chain_${chain_id}.yaml:/configs/chain_${chain_id}.yaml:ro
      - $configs_dir/genesis.json:/app/local-chains/${version}/genesis.json:ro
    depends_on:
      l1:
        condition: service_healthy${gateway_dep}
    healthcheck:
      test: ['CMD', '/usr/bin/bash', '-c', 'exec 3<>/dev/tcp/127.0.0.1/${int_port}']
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s

volumes:
  ${db_vol}:
EOF
  log "Generated $out"
}

# ── main ──────────────────────────────────────────────────────────────────────
main() {
  generate_l1

  if [[ "$gateway" == true ]]; then
    generate_gateway
  fi

  local i
  for i in $(seq 1 "$count"); do
    generate_chain "$i"
  done

  local mode_label="L1 settlement"
  [[ "$gateway" == true ]] && mode_label="gateway settlement (chain 506 → L1)"
  log "Done. $count chain compose file(s) + L1${gateway:+ + gateway} written to: $output_dir  [$mode_label]"
}

main
