#!/usr/bin/env bash
# generate-prividium-compose.sh
# Generates composable docker-compose files for N Prividium instances:
#   <output-dir>/docker-compose.l1.yml              (shared L1 — Anvil)
#   <output-dir>/docker-compose.prividium-<id>.yml  (one full stack per instance)
#
# Port layout per instance N (1-indexed), offset = (N-1)*200:
#   zksyncos RPC  : 5050 + offset  (external)  →  3050 (internal)
#   admin-panel   : 3000 + offset
#   user-panel    : 3001 + offset
#   prividium-api : 8000 + offset
#   api metrics   : 9091 + offset
#   keycloak      : 5080 + offset
#   postgres      : 5432 + offset
#   block-explorer: 3010 + offset
#   data-fetcher  : 3040 + offset
#   explorer-api  : 3002 + offset

set -euo pipefail

readonly SCRIPT_NAME="generate-prividium-compose.sh"

# ── defaults ──────────────────────────────────────────────────────────────────
readonly DEFAULT_COUNT=1
readonly DEFAULT_VERSION="v30.2"
readonly DEFAULT_SERVER_IMAGE="ghcr.io/matter-labs/zksync-os-server:latest"
readonly DEFAULT_L1_IMAGE="ghcr.io/foundry-rs/foundry:v1.3.4"
readonly DEFAULT_PRIVIDIUM_VERSION="v1.153.1"
readonly BASE_CHAIN_ID=6564
readonly PORT_STRIDE=200

# ── helpers ───────────────────────────────────────────────────────────────────
die()        { echo "[$SCRIPT_NAME] ERROR: $*" >&2; exit 1; }
log()        { echo "[$SCRIPT_NAME] $*"; }
is_integer() { [[ "$1" =~ ^[0-9]+$ ]]; }

usage() {
  cat <<EOF
Usage: $SCRIPT_NAME [OPTIONS]

Generates composable docker-compose files for N Prividium instances.

Options:
  --count=N              Number of Prividium instances (default: $DEFAULT_COUNT)
  --output-dir=DIR       Directory to write compose files (required)
  --configs-dir=DIR      Directory containing chain configs and genesis (required)
  --version=VER          ZKsync OS protocol version (default: $DEFAULT_VERSION)
  --server-image=IMG     zksync-os-server image (default: $DEFAULT_SERVER_IMAGE)
  --l1-image=IMG         Anvil image (default: $DEFAULT_L1_IMAGE)
  --prividium-version=V  Prividium services image tag (default: $DEFAULT_PRIVIDIUM_VERSION)
  --help, -h             Show this message
EOF
  exit 0
}

# ── argument parsing ──────────────────────────────────────────────────────────
count="$DEFAULT_COUNT"
output_dir=""
configs_dir=""
version="$DEFAULT_VERSION"
server_image="$DEFAULT_SERVER_IMAGE"
l1_image="$DEFAULT_L1_IMAGE"
prividium_version="$DEFAULT_PRIVIDIUM_VERSION"

for arg in "$@"; do
  case "$arg" in
    --count=*)              count="${arg#*=}" ;;
    --output-dir=*)         output_dir="${arg#*=}" ;;
    --configs-dir=*)        configs_dir="${arg#*=}" ;;
    --version=*)            version="${arg#*=}" ;;
    --server-image=*)       server_image="${arg#*=}" ;;
    --l1-image=*)           l1_image="${arg#*=}" ;;
    --prividium-version=*)  prividium_version="${arg#*=}" ;;
    --help|-h)              usage ;;
    *) die "Unknown argument: $arg" ;;
  esac
done

[[ -n "$output_dir"  ]] || die "--output-dir is required"
[[ -n "$configs_dir" ]] || die "--configs-dir is required"
is_integer "$count"    || die "--count must be a positive integer"
[[ "$count" -ge 1 ]]   || die "--count must be at least 1"

configs_dir="$(realpath "$configs_dir")"
mkdir -p "$output_dir"

# ── l1 compose file ───────────────────────────────────────────────────────────
generate_l1() {
  local out="$output_dir/docker-compose.l1.yml"
  cat > "$out" <<EOF
# Auto-generated by $SCRIPT_NAME — do not edit manually.
name: zksync-prividiums

services:
  l1:
    image: $l1_image
    volumes:
      - $configs_dir/l1-state.json.gz:/l1-state.json.gz:ro
      - l1state:/home/foundry/l1state
    entrypoint: ''
    user: 'root'
    ports:
      - '5010:5010'
    healthcheck:
      test: ['CMD-SHELL', 'cast chain-id -r http://localhost:5010']
      interval: 10s
      timeout: 5s
      retries: 5
    command: |
      bash -c "
      if [[ ! -f /home/foundry/l1state/state.json ]]; then
        echo 'Decompressing L1 state...'
        gzip -d < /l1-state.json.gz > /home/foundry/l1state/state.json
      fi
      anvil --state=/home/foundry/l1state/state.json --preserve-historical-states --port 5010 --host 0.0.0.0
      "

volumes:
  l1state:
EOF
  log "Generated $out"
}

# ── block-explorer config.js ──────────────────────────────────────────────────
generate_explorer_config() {
  local -r instance_num="$1"
  local -r chain_id="$2"
  local -r api_port="$3"
  local -r explorer_app_port="$4"
  local -r user_panel_port="$5"
  local -r zksyncos_ext="$6"
  local -r out_dir="$7"

  mkdir -p "$out_dir"
  cat > "$out_dir/block-explorer-config.js" <<EOF
window['##runtimeConfig'] = {
  "appEnvironment": "prividium",
  "environmentConfig": {
    "networks": [{
      "apiUrl": "http://localhost:${api_port}",
      "hostnames": ["localhost:${explorer_app_port}"],
      "rpcUrl": "http://localhost:${api_port}/rpc",
      "l2ChainId": ${chain_id},
      "l2NetworkName": "Prividium Local (${chain_id})",
      "baseTokenAddress": "0x000000000000000000000000000000000000800A",
      "l2WalletUrl": "http://localhost:${user_panel_port}",
      "published": true,
      "maintenance": false
    }]
  }
};
EOF
}

# ── per-instance prividium compose file ───────────────────────────────────────
generate_prividium() {
  local -r instance_num="$1"
  local -r chain_id=$(( BASE_CHAIN_ID + instance_num ))
  local -r offset=$(( (instance_num - 1) * PORT_STRIDE ))

  # External ports (host-visible)
  local -r p_zksyncos=$(( 5050 + offset ))
  local -r p_admin=$(( 3000 + offset ))
  local -r p_user=$(( 3001 + offset ))
  local -r p_api=$(( 8000 + offset ))
  local -r p_api_metrics=$(( 9091 + offset ))
  local -r p_keycloak=$(( 5080 + offset ))
  local -r p_postgres=$(( 5432 + offset ))
  local -r p_explorer_app=$(( 3010 + offset ))
  local -r p_explorer_api=$(( 3002 + offset ))
  local -r p_data_fetcher=$(( 3040 + offset ))

  # Service name suffix (chain ID)
  local -r s="${chain_id}"

  # Keycloak hostname (for token/jwks URLs shown to the browser)
  local -r kc_host="http://localhost:${p_keycloak}"

  # Config sub-directory for per-instance static files
  local -r cfg_subdir="$configs_dir/prividium-${chain_id}"
  generate_explorer_config \
    "$instance_num" "$chain_id" "$p_explorer_api" "$p_explorer_app" \
    "$p_user" "$p_zksyncos" "$cfg_subdir"

  local -r out="$output_dir/docker-compose.prividium-${chain_id}.yml"

  cat > "$out" <<EOF
# Auto-generated by $SCRIPT_NAME — do not edit manually.
# Prividium instance for chain ID: $chain_id
# Ports: zksyncos=$p_zksyncos admin=$p_admin user=$p_user api=$p_api keycloak=$p_keycloak
name: zksync-prividiums

services:

  # ── postgres ────────────────────────────────────────────────────────────────
  postgres-${s}:
    image: postgres:15
    restart: unless-stopped
    ports:
      - '${p_postgres}:5432'
    volumes:
      - postgres_${s}:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    entrypoint: |
      bash -c "
      cat > /docker-entrypoint-initdb.d/init.sql << 'SQLEOF'
      CREATE DATABASE prividium_api;
      CREATE DATABASE prividium_block_explorer;
      SQLEOF
      exec docker-entrypoint.sh postgres
      "

  # ── keycloak ────────────────────────────────────────────────────────────────
  keycloak-${s}:
    image: quay.io/keycloak/keycloak:26.0
    ports:
      - '${p_keycloak}:8080'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_RELATIVE_PATH: /
      KC_HEALTH_ENABLED: 'true'
      KC_HTTP_ENABLED: 'true'
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      KC_HOSTNAME_URL: '${kc_host}'
      KC_HOSTNAME_ADMIN_URL: '${kc_host}'
    command:
      - start-dev
      - --import-realm
    volumes:
      - $configs_dir/keycloak-realm.json:/opt/keycloak/data/import/realm-export.json:ro
    healthcheck:
      test: ['CMD-SHELL', 'exec 3<>/dev/tcp/127.0.0.1/8080']
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s

  # ── zksyncos sequencer ───────────────────────────────────────────────────────
  zksyncos-${s}:
    image: $server_image
    platform: linux/amd64
    ports:
      - '${p_zksyncos}:3050'
    environment:
      GENERAL_L1_RPC_URL: 'http://l1:5010'
    user: 'root'
    working_dir: '/app'
    entrypoint: ''
    command: ['/usr/bin/tini', '--', 'zksync-os-server', '--config', '/configs/chain_${chain_id}.yaml']
    volumes:
      - zksyncos_${s}_db:/db
      - $configs_dir/chain_${chain_id}.yaml:/configs/chain_${chain_id}.yaml:ro
      - $configs_dir/genesis.json:/app/local-chains/${version}/genesis.json:ro
    depends_on:
      l1:
        condition: service_healthy
    healthcheck:
      test: ['CMD', '/usr/bin/bash', '-c', 'exec 3<>/dev/tcp/127.0.0.1/3050']
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s

  # ── prividium-api ────────────────────────────────────────────────────────────
  prividium-api-${s}:
    image: quay.io/matterlabs_enterprise/prividium-permissions-api:${prividium_version}
    platform: linux/amd64
    restart: unless-stopped
    depends_on:
      postgres-${s}:
        condition: service_healthy
      zksyncos-${s}:
        condition: service_healthy
    ports:
      - '${p_api}:8000'
      - '${p_api_metrics}:9091'
    environment:
      - PORT=8000
      - METRICS_PORT=9091
      - SEQUENCER_RPC_URL=http://zksyncos-${s}:3050
      - DATABASE_URL=postgres://postgres:postgres@postgres-${s}:5432/prividium_api
      - CORS_ORIGIN=http://localhost:${p_admin},http://localhost:${p_user}
      - AUTH_METHODS=oidc,crypto_native
      - NODE_ENV=production
      - SIWE_CHAIN_ID=${chain_id}
      - SIWE_VALID_DOMAINS=localhost:${p_admin},localhost:${p_user}
      - OIDC_JWKS_URI=http://keycloak-${s}:8080/realms/prividium/protocol/openid-connect/certs
      - OIDC_JWT_AUD=prividium-client
      - OIDC_JWT_ISSUER=${kc_host}/realms/prividium
      - OIDC_ADMIN_SUBS=00000000-0000-0000-0000-000000000001
      - CORS_CACHE_DURATION_MS=600000
      - ADMIN_PANEL_REDIRECT_URLS=http://localhost:${p_admin}/callback
      - BLOCK_EXPLORER_REDIRECT_URLS=http://localhost:${p_explorer_app}/auth/callback
      - WALLETS_API_ENABLED=true
      - WEBAUTHN_RP_NAME=ZKsync Prividium
      - WEBAUTHN_RP_ID=localhost
      - WEBAUTHN_ORIGIN=http://localhost:${p_user}
      - WEBAUTHN_REQUIRE_USER_VERIFICATION=false
      - EXTRA_PUBLIC_CODE_ADDRESSES=0x36615cf349d7f6344891b1e7ca7c72883f5dc049

  # ── admin panel ──────────────────────────────────────────────────────────────
  admin-panel-${s}:
    image: quay.io/matterlabs_enterprise/prividium-adminv2:${prividium_version}
    platform: linux/amd64
    restart: unless-stopped
    environment:
      - VITE_PRIVIDIUM_API_URL=http://localhost:${p_api}
      - VITE_USER_PANEL_URL=http://localhost:${p_user}
      - VITE_EXPLORER_URL=http://localhost:${p_explorer_app}
      - PORT=3000
    depends_on:
      - prividium-api-${s}
    ports:
      - '${p_admin}:3000'

  # ── user panel ───────────────────────────────────────────────────────────────
  user-panel-${s}:
    image: quay.io/matterlabs_enterprise/prividium-user-panel:${prividium_version}
    platform: linux/amd64
    restart: unless-stopped
    environment:
      - VITE_OIDC_AUTHORITY=${kc_host}/realms/prividium
      - VITE_OIDC_CLIENT_ID=prividium-client
      - VITE_OIDC_REDIRECT_URI=http://localhost:${p_user}/callback
      - VITE_OIDC_POST_LOGOUT_REDIRECT_URI=http://localhost:${p_user}/login
      - VITE_OIDC_BUTTON_TEXT=Sign in with Keycloak
      - VITE_ADMIN_PANEL_REDIRECT_URI=http://localhost:${p_admin}/callback
      - VITE_AUTH_METHODS=oidc,crypto_native
      - VITE_CHAIN_ID=${chain_id}
      - VITE_CHAIN_NAME=Prividium Local
      - VITE_WALLETS_ENABLED=true
      - VITE_BRIDGING_ENABLED=true
      - VITE_L1_RPC_URL=http://localhost:5010
      - VITE_L1_CHAIN_ID=31337
      - VITE_L1_CHAIN_NAME=Anvil Localhost
      - VITE_PRIVIDIUM_API_URL=http://localhost:${p_api}
      - VITE_EXPLORER_URL=http://localhost:${p_explorer_app}
      - VITE_ADMIN_PANEL_URL=http://localhost:${p_admin}
      - VITE_REOWN_PROJECT_ID=
      - PORT=3000
    depends_on:
      - prividium-api-${s}
    ports:
      - '${p_user}:3000'

  # ── block explorer ───────────────────────────────────────────────────────────
  block-explorer-api-${s}:
    image: ghcr.io/matter-labs/block-explorer-api:latest
    platform: linux/amd64
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      LOG_LEVEL: verbose
      NODE_ENV: development
      DATABASE_HOST: postgres-${s}
      DATABASE_NAME: prividium_block_explorer
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_ENABLE_SSL: 'false'
      NETWORK_NAME: testnet
      PRIVIDIUM: 'true'
      PRIVIDIUM_APP_URL: http://localhost:${p_explorer_app}
      PRIVIDIUM_PERMISSIONS_API_URL: http://host.docker.internal:${p_api}
      PRIVIDIUM_SESSION_SECRET: QkxPQ0tfRVhQTE9SRVJfU0VTU0lPTl9TRUNSRVQ=
      PRIVIDIUM_SESSION_MAX_AGE: 86400000
      PRIVIDIUM_SESSION_SAME_SITE: strict
      LIMITED_PAGINATION_MAX_ITEMS: '10000'
      API_LIMITED_PAGINATION_MAX_ITEMS: '1000'
      DISABLE_BFF_API_SCHEMA_DOCS: 'true'
    ports:
      - '${p_explorer_api}:3000'
    depends_on:
      postgres-${s}:
        condition: service_healthy

  block-explorer-data-fetcher-${s}:
    image: ghcr.io/matter-labs/block-explorer-data-fetcher:latest
    platform: linux/amd64
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      NETWORK_NAME: testnet
      BLOCKCHAIN_RPC_URL: http://zksyncos-${s}:3050
      PRIVIDIUM: 'true'
      PRIVIDIUM_PERMISSIONS_API_URL: http://host.docker.internal:${p_api}/api
    ports:
      - '${p_data_fetcher}:3040'

  block-explorer-worker-${s}:
    image: ghcr.io/matter-labs/block-explorer-worker:latest
    platform: linux/amd64
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      DATABASE_HOST: postgres-${s}
      DATABASE_NAME: prividium_block_explorer
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_ENABLE_SSL: 'false'
      NETWORK_NAME: testnet
      BLOCKCHAIN_RPC_URL: http://zksyncos-${s}:3050
      DATA_FETCHER_URL: http://block-explorer-data-fetcher-${s}:3040
      PRIVIDIUM: 'true'
      PRIVIDIUM_PERMISSIONS_API_URL: http://host.docker.internal:${p_api}/api
      ENABLE_TOKEN_OFFCHAIN_DATA_SAVER: 'true'
      BLOCKS_PROCESSING_BATCH_SIZE: '10'
      NUMBER_OF_BLOCKS_PER_DB_TRANSACTION: '10'
    depends_on:
      postgres-${s}:
        condition: service_healthy
      block-explorer-data-fetcher-${s}:
        condition: service_started

  block-explorer-app-${s}:
    image: ghcr.io/matter-labs/block-explorer-app:latest
    platform: linux/amd64
    volumes:
      - $cfg_subdir/block-explorer-config.js:/usr/share/nginx/html/config.js:ro
    ports:
      - '${p_explorer_app}:3010'
    depends_on:
      block-explorer-api-${s}:
        condition: service_started

volumes:
  postgres_${s}:
  zksyncos_${s}_db:
EOF
  log "Generated $out"
}

# ── main ──────────────────────────────────────────────────────────────────────
main() {
  generate_l1

  local i
  for i in $(seq 1 "$count"); do
    generate_prividium "$i"
  done

  log "Done. $count prividium compose file(s) + 1 L1 compose file written to: $output_dir"
}

main
