#!/usr/bin/env bash
# generate-compose.sh
# Generates composable docker-compose files for N ZKsync OS L2 chains:
#   <output-dir>/docker-compose.l1.yml
#   <output-dir>/docker-compose.zksyncos-<chain_id>.yml  (one per chain)

set -euo pipefail

readonly SCRIPT_NAME="generate-compose.sh"

# ── defaults ────────────────────────────────────────────────────────────────
readonly DEFAULT_COUNT=2
readonly DEFAULT_VERSION="v30.2"
readonly DEFAULT_SERVER_IMAGE="ghcr.io/matter-labs/zksync-os-server:latest"
readonly DEFAULT_L1_IMAGE="ghcr.io/foundry-rs/foundry:v1.3.4"
readonly BASE_CHAIN_ID=6564

# ── helpers ──────────────────────────────────────────────────────────────────
die()   { echo "[$SCRIPT_NAME] ERROR: $*" >&2; exit 1; }
log()   { echo "[$SCRIPT_NAME] $*"; }
is_integer() { [[ "$1" =~ ^[0-9]+$ ]]; }

usage() {
  cat <<EOF
Usage: $SCRIPT_NAME [OPTIONS]

Generates composable docker-compose files for N ZKsync OS L2 chains.

Options:
  --count=N           Number of L2 chains (default: $DEFAULT_COUNT)
  --output-dir=DIR    Directory to write compose files into (required)
  --configs-dir=DIR   Directory containing chain configs and genesis (required)
  --version=VER       ZKsync OS version (default: $DEFAULT_VERSION)
  --server-image=IMG  zksync-os-server Docker image (default: $DEFAULT_SERVER_IMAGE)
  --l1-image=IMG      L1 / Anvil Docker image (default: $DEFAULT_L1_IMAGE)
  --help, -h          Show this message

Output files:
  <output-dir>/docker-compose.l1.yml
  <output-dir>/docker-compose.zksyncos-<chain_id>.yml  (one per chain)
EOF
  exit 0
}

# ── argument parsing ──────────────────────────────────────────────────────────
count="$DEFAULT_COUNT"
output_dir=""
configs_dir=""
version="$DEFAULT_VERSION"
server_image="$DEFAULT_SERVER_IMAGE"
l1_image="$DEFAULT_L1_IMAGE"

for arg in "$@"; do
  case "$arg" in
    --count=*)        count="${arg#*=}" ;;
    --output-dir=*)   output_dir="${arg#*=}" ;;
    --configs-dir=*)  configs_dir="${arg#*=}" ;;
    --version=*)      version="${arg#*=}" ;;
    --server-image=*) server_image="${arg#*=}" ;;
    --l1-image=*)     l1_image="${arg#*=}" ;;
    --help|-h)        usage ;;
    *) die "Unknown argument: $arg" ;;
  esac
done

[[ -n "$output_dir"  ]] || die "--output-dir is required"
[[ -n "$configs_dir" ]] || die "--configs-dir is required"
is_integer "$count"    || die "--count must be a positive integer"
[[ "$count" -ge 1 ]]   || die "--count must be at least 1"

# Resolve absolute paths for volume mounts
configs_dir="$(realpath "$configs_dir")"
mkdir -p "$output_dir"

# ── l1 compose file ───────────────────────────────────────────────────────────
generate_l1() {
  local out="$output_dir/docker-compose.l1.yml"
  cat > "$out" <<EOF
# Auto-generated by $SCRIPT_NAME — do not edit manually.
name: zksync-l2s

services:
  l1:
    image: $l1_image
    volumes:
      - $configs_dir/l1-state.json.gz:/l1-state.json.gz:ro
      - l1state:/home/foundry/l1state
    entrypoint: ''
    user: 'root'
    ports:
      - '5010:5010'
    healthcheck:
      test: ['CMD-SHELL', 'cast chain-id -r http://localhost:5010']
      interval: 10s
      timeout: 5s
      retries: 5
    command: |
      bash -c "
      if [[ ! -f /home/foundry/l1state/state.json ]]; then
        echo 'Decompressing L1 state...'
        gzip -d < /l1-state.json.gz > /home/foundry/l1state/state.json
      fi
      anvil --state=/home/foundry/l1state/state.json --preserve-historical-states --port 5010 --host 0.0.0.0
      "

volumes:
  l1state:
EOF
  log "Generated $out"
}

# ── per-chain compose file ────────────────────────────────────────────────────
generate_chain() {
  local chain_num="$1"
  local chain_id=$(( BASE_CHAIN_ID + chain_num ))
  local int_port=$(( 3049 + chain_num ))   # 3050, 3051, 3052, ...
  local ext_port=$(( 5049 + chain_num ))   # 5050, 5051, 5052, ...
  local db_vol="zksyncos_${chain_id}_db"
  local out="$output_dir/docker-compose.zksyncos-${chain_id}.yml"

  cat > "$out" <<EOF
# Auto-generated by $SCRIPT_NAME — do not edit manually.
# Chain ID: $chain_id  |  RPC: localhost:$ext_port
name: zksync-l2s

services:
  zksyncos-${chain_id}:
    image: $server_image
    platform: linux/amd64
    ports:
      - '${ext_port}:${int_port}'
    environment:
      GENERAL_L1_RPC_URL: 'http://l1:5010'
    user: 'root'
    working_dir: '/app'
    entrypoint: ''
    command: ['/usr/bin/tini', '--', 'zksync-os-server', '--config', '/configs/chain_${chain_id}.yaml']
    volumes:
      - ${db_vol}:/db
      - $configs_dir/chain_${chain_id}.yaml:/configs/chain_${chain_id}.yaml:ro
      - $configs_dir/genesis.json:/app/local-chains/${version}/genesis.json:ro
    depends_on:
      l1:
        condition: service_healthy
    healthcheck:
      test: ['CMD', '/usr/bin/bash', '-c', 'exec 3<>/dev/tcp/127.0.0.1/${int_port}']
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s

volumes:
  ${db_vol}:
EOF
  log "Generated $out"
}

# ── main ──────────────────────────────────────────────────────────────────────
main() {
  generate_l1

  local i
  for i in $(seq 1 "$count"); do
    generate_chain "$i"
  done

  log "Done. $count chain compose file(s) + 1 L1 compose file written to: $output_dir"
}

main
